Fix https://github.com/ubports/libertine/issues/33
ubports/libertine pull request #34
Opened 2019-04-07 14:14 UTC by arubislander

After the transition from `PageStack` to `AdaptivePageLayout` for the Libertine configuration views some more fixes where needed:
`Page.pageStack.currentPage` is undefined for an `AdaptivePageLayout` so the `installPackage()` method on the `ContainerEditView` was no longer being called.

I added a property `homeView` to `DebianPackagePicker` and `SearchResultsView`, pass the instance of `ContainerEditView` (which has the id of _homeView_) to them and access the method via this property.

2019-04-12 21:15 UTC, dobey commented
Hmm. I think it would be better instead to provide a common signal which the pages emit, and which is connected when creating those page components, rather than passing the home view in as a property, and then calling a method on it.

2019-04-12 22:03 UTC, arubislander commented
Thanks for the feedback. Will look into it at the first opportunity.

2019-04-23 14:46 UTC, arubislander commented
Have added a commit following your pointers and suggestion

2019-05-28 14:20 UTC, dobey requested changes

2019-05-28 14:20 UTC, dobey commented on qml/common/DebianPackagePicker.qml
> +    signal packageSelected( string packageName )
Please remove the extra whitespace inside the parentheses.

2019-05-28 14:20 UTC, dobey commented on qml/common/DebianPackagePicker.qml
> +            debianPackagePicker.packageSelected( containerConfigList.getDownloadsLocation() + "/" + fileName )
Please remove the extra starting/ending whitespace inside parentheses.

2019-05-28 14:20 UTC, dobey commented on qml/common/SearchResultsView.qml
> +    signal packageSelected( string packageName )
Please remove the extra whitespace to keep consistent with the code.

2019-05-28 16:21 UTC, dobey approved these changes
Looks OK now. Would be nice to have tests for this stuff too, but it looks like there are no tests for the QML at all yet, so I won't block your changes on that. Thanks!

2019-05-28 16:22 UTC, merged